acc bang dap
DavyCraft648/MCFurniture pull request #8
Opened 2023-06-24 12:13 UTC by ZhorifCraft451

2023-06-24 12:29 UTC, DavyCraft648 requested changes

2023-06-24 12:29 UTC, DavyCraft648 commented on src/block/ShowerHead.php
> +	use HorizontalFacingTrait;
```suggestion
class ShowerHead extends \pocketmine\block\Transparent implements \customiesdevs\customies\block\permutations\Permutable{
	use HorizontalFacingTrait;
```

2023-06-24 12:29 UTC, DavyCraft648 commented on src/block/Shower.php
> +class Shower extends \pocketmine\block\Transparent implements Permutable{
aku sebenernya ga terlalu yakin ini harusnya termasuk Permutable apa ngga.. perasaan geometrynya di tiap sisi ga ada bedanya? (tolong koreksi)

2023-06-24 12:29 UTC, DavyCraft648 commented on src/block/Shower.php
> +	public function getPermutations() : array{
```suggestion
	}

	public function getPermutations() : array{
```

2023-06-24 12:29 UTC, DavyCraft648 commented on src/block/Shower.php
> +			(new Permutation("q.block_property('facing_direction'') == 2"))
.

2023-06-24 12:29 UTC, DavyCraft648 commented on src/block/Shower.php
> +			(new Permutation("q.block_property('facing_direction'') == 3"))
.

2023-06-24 12:29 UTC, DavyCraft648 commented on src/block/Shower.php
> +	public function getCurrentBlockProperties() : array{
```suggestion
	}

	public function getCurrentBlockProperties() : array{
```

2023-06-24 12:29 UTC, DavyCraft648 commented on src/block/Shower.php
> +	protected function describeBlockOnlyState(RuntimeDataDescriber $w) : void{
```suggestion
	}

	protected function describeBlockOnlyState(RuntimeDataDescriber $w) : void{
```

2023-06-24 12:29 UTC, DavyCraft648 commented on src/block/ShowerHead.php
> +	public function getCurrentBlockProperties() : array{
```suggestion
	}

	public function getCurrentBlockProperties() : array{
```

2023-06-24 12:29 UTC, DavyCraft648 commented on src/utils/SitUtils.php
> +
.

2023-06-24 12:29 UTC, DavyCraft648 commented on src/utils/SitUtils.php
> +
.

2023-06-24 12:29 UTC, DavyCraft648 commented on src/utils/SitUtils.php
> +
.

2023-06-24 12:29 UTC, DavyCraft648 commented on src/block/ShowerHead.php
> +	protected function describeBlockOnlyState(RuntimeDataDescriber $w) : void{
```suggestion
	}

	protected function describeBlockOnlyState(RuntimeDataDescriber $w) : void{
```

2023-06-24 12:36 UTC, ZhorifCraft451 commented on src/block/Shower.php
> +class Shower extends \pocketmine\block\Transparent implements Permutable{
hmmm, iya juga y, yodah ane hapus dulu

2023-06-24 12:39 UTC, ZhorifCraft451 commented on src/block/Shower.php
> +			(new Permutation("q.block_property('facing_direction'') == 2"))
ini apanya banh

2023-06-24 12:39 UTC, ZhorifCraft451 commented on src/block/Shower.php
> +			(new Permutation("q.block_property('facing_direction'') == 3"))
ini juga

2023-06-24 12:39 UTC, ZhorifCraft451 commented on src/utils/SitUtils.php
> +
ini juga

2023-06-24 12:39 UTC, ZhorifCraft451 commented on src/utils/SitUtils.php
> +
ini juga

2023-06-24 12:39 UTC, ZhorifCraft451 commented on src/utils/SitUtils.php
> +
?

2023-06-24 12:45 UTC, ZhorifCraft451 commented on src/block/Shower.php
> +			(new Permutation("q.block_property('facing_direction'') == 2"))
disamain aja kah conditionnya jadi pakai statement and

2023-06-24 12:46 UTC, ZhorifCraft451 commented
![image](https://github.com/DavyCraft648/MCFurniture/assets/75656616/15642c7f-25c1-4444-93f1-7f04fe14b108)


kosongin aja kah yg shower?, soalnya sama aja keknya di geometri ny

2023-06-24 12:54 UTC, ZhorifCraft451 commented
udah bang dap, cobain

2023-06-24 12:56 UTC, ZhorifCraft451 commented
eh pake permutable, aku coba malah error

2023-06-24 12:59 UTC, ZhorifCraft451 commented
yeh malah error total abis di revisi, wes ngulang lah

2023-06-24 13:06 UTC, ZhorifCraft451 commented
dah

2023-06-24 13:09 UTC, ZhorifCraft451 commented
@DavyCraft648

2023-06-25 08:50 UTC, ZhorifCraft451 commented
@DavyCraft648 silahkan, koreksi kan lagi

2023-06-25 14:39 UTC, ZhorifCraft451 commented
maaf merepotkan

2023-07-15 11:35 UTC, closed without merging